version: '3'

services:
    json_server:
        image: node:latest
        working_dir: /json_serv
        volumes:
        - ./json_server:/json_serv
        command: bash script_pipe.sh
        # expose: 
        # - 8000
        ports:
            -   "8000:8000"

    lite_server:
        image: node:latest
        working_dir: /lite_serv
        volumes:
        - ./lite_server:/lite_serv
        command: bash script_pipe.sh
        # expose:
        # - 3000
        ports:
            -   "3000:3000"
        
    nginx:
        image: nginx
        volumes:
        - ./templates:/etc/nginx/templates/nginx.conf
        ports:
        - "80:80"
        environment:
        - NGINX_HOST=0.0.0.0
        - NGINX_PORT=80
        links: 
        - json_server
        - lite_server
       


       